import os


def generate_risk_report(test_results, summary_text=""):
    """
    Generates a 2026-style Risk Coverage Dashboard in Markdown.
    Ranks failures by risk level (Impact x Probability).
    """
    _RISK_LABELS = {"high": "🔴 High", "medium": "🟡 Medium", "low": "🟢 Low"}

    report = "# 📊 Risk Coverage Dashboard\n\n"

    if summary_text:
        report += f"## 📝 Executive Summary\n{summary_text}\n\n"

    report += "## 🔍 Detailed Results\n"
    report += "| Area | Status | Risk Level | Healing Status | Notes |\n"
    report += "| :--- | :--- | :--- | :--- | :--- |\n"

    for area in test_results:
        risk_label = _RISK_LABELS.get(area.get("risk", "medium"), "🟡 Medium")
        status_icon = "✅" if area["status"] == "pass" else "❌"
        healed_icon = "🩹 Healed" if area.get("healed") else "N/A"
        report += f"| {area['name']} | {status_icon} | {risk_label} | {healed_icon} | {area['notes']} |\n"

    report += "\n\n---\n*Generated by Agentic QA Lab v1.0 (2026 Edition)*"

    os.makedirs("output", exist_ok=True)
    with open("output/risk_report.md", "w") as f:
        f.write(report)

    print("📈 Risk Dashboard generated: output/risk_report.md")


if __name__ == "__main__":
    # Mock data for demonstration
    mock_results = [
        {"name": "Checkout Button", "status": "fail", "risk": "high", "healed": True, "notes": "Selector shifted from .btn-checkout to .btn-pay"},
        {"name": "Login Flow", "status": "pass", "risk": "high", "healed": False, "notes": "No issues detected"},
        {"name": "Search Function", "status": "pass", "risk": "low", "healed": False, "notes": "Passed first attempt"},
    ]
    generate_risk_report(mock_results, "The squad successfully identified and healed a UI shift in the checkout flow.")
